cmake_minimum_required(VERSION 3.27...4.3)
project(miniCDi VERSION 0.11 LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
set(APP_AUTHOR "Mr. Lechkar aka CatmanFan")
include(CMakeDependentOption)

# Debug options
option(MINICDI_DISABLE_VERBOSE "Completely disable verbose logging of any kind." OFF)
cmake_dependent_option(MINICDI_ENABLE_VERBOSE_DISPLAY "Force-enable verbose output display." OFF
                        "NOT MINICDI_DISABLE_VERBOSE" OFF)
option(MINICDI_ENABLE_VERBOSE_DISPLAY_CPU "Print verbose CPU information (PC, SR, FC, D*, A*)." OFF)
option(MINICDI_ENABLE_VERBOSE_OS9 "Print OS-9 syscalls to verbose." OFF)
option(MINICDI_ENABLE_VERBOSE_MODULE "Prefix verbose with OS-9 modules and addresses." OFF)
option(MINICDI_ENABLE_FORCE_LOGFILE "Always use the verbose log to text file option." OFF)

# Emulation options
cmake_dependent_option(MINICDI_DISABLE_DISC_IFSTREAM "Use C library FILE* instead of std::ifstream for disc sectors." OFF # This seems to be broken on Windows.
                        "NOT WIN32;NOT APPLE" OFF)
option(MINICDI_ENABLE_BENCHMARK "Log duration of frame execution." OFF)

# Compilation config
# -------------------------------------------
add_executable(${PROJECT_NAME})
if (WIN32)
    target_compile_options(${PROJECT_NAME} PRIVATE -O3 -fomit-frame-pointer -fno-math-errno -Wall)
elseif (APPLE)
    target_compile_options(${PROJECT_NAME} PRIVATE -O3 -fomit-frame-pointer -fno-math-errno -Wall)
else() # DevKitPro
    dkp_target_generate_symbol_list(${PROJECT_NAME})
    target_compile_options(${PROJECT_NAME} PRIVATE -O3 -fomit-frame-pointer -fno-math-errno -flto=auto -DNDEBUG -Wall)
endif()

if (MINICDI_DISABLE_VERBOSE)
    MESSAGE(STATUS "MINICDI_DISABLE_VERBOSE")
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_NOLOG)
endif()
if (MINICDI_ENABLE_VERBOSE_DISPLAY)
    MESSAGE(STATUS "MINICDI_ENABLE_VERBOSE_DISPLAY")
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_DEBUG)
    if (MINICDI_ENABLE_VERBOSE_DISPLAY_CPU)
        MESSAGE(STATUS "MINICDI_ENABLE_VERBOSE_DISPLAY_CPU")
        target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_DEBUG_CPU)
    endif()
endif()
if (MINICDI_ENABLE_VERBOSE_OS9)
    MESSAGE(STATUS "MINICDI_ENABLE_VERBOSE_OS9")
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_DEBUG_OS9)
endif()
if (MINICDI_ENABLE_VERBOSE_MODULE)
    MESSAGE(STATUS "MINICDI_ENABLE_VERBOSE_MODULE")
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_DEBUG_MODULE)
endif()
if (MINICDI_ENABLE_FORCE_LOGFILE)
    MESSAGE(STATUS "MINICDI_ENABLE_FORCE_LOGFILE")
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_FORCE_LOGFILE)
endif()

if (MINICDI_DISABLE_DISC_IFSTREAM)
    MESSAGE(STATUS "MINICDI_DISABLE_DISC_IFSTREAM")
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_NO_DISC_IFSTREAM)
endif()
if (MINICDI_ENABLE_BENCHMARK)
    MESSAGE(STATUS "MINICDI_ENABLE_BENCHMARK")
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_BENCHMARKING)
endif()

# Core source files
# -------------------------------------------
target_include_directories(${PROJECT_NAME} PRIVATE src src/cdi/m68k)
file(GLOB_RECURSE MINICDI_SOURCE_FILES LIST_DIRECTORIES false
    src/cdi/*.c
    src/cdi/*.cpp
)
target_sources(${PROJECT_NAME} PRIVATE ${MINICDI_SOURCE_FILES})

# Platform build specific
# -------------------------------------------

if (WIN32 OR APPLE)
    find_package(SDL2 REQUIRED)
    include_directories(${SDL2_INCLUDE_DIRS})
    find_package(wxWidgets COMPONENTS core)
    target_link_libraries(${PROJECT_NAME} PRIVATE wxWidgets::wxWidgets ${SDL2_LIBRARIES})
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_AUDIO=1) # SDL2

    if (MINICDI_ENABLE_VERBOSE_DISPLAY)
        set_target_properties(${PROJECT_NAME} PROPERTIES WIN32_EXECUTABLE FALSE)
    else()
        set_target_properties(${PROJECT_NAME} PROPERTIES WIN32_EXECUTABLE TRUE)
    endif()

    target_include_directories(${PROJECT_NAME} PRIVATE src/frontends/wx)
    target_sources(${PROJECT_NAME} PRIVATE
        src/frontends/wx/mainFrame.cpp
        src/frontends/wx/uiLauncher.cpp
    )

    if (WIN32)
        target_sources(${PROJECT_NAME} PRIVATE res/win/windows.rc)
    endif()
endif()

if (NINTENDO_3DS)
    target_link_libraries(${PROJECT_NAME} PRIVATE -lcitro2d -lcitro3d)

    target_include_directories(${PROJECT_NAME} PRIVATE
        src/platforms/common/imgui
        src/frontends/imgui_3ds
    )

    ctr_add_shader_library(vshader src/platforms/common/imgui/backends/vshader.v.pica)
    dkp_add_embedded_binary_library(vshader_data vshader)
    target_link_libraries(${PROJECT_NAME} PRIVATE vshader_data)

    target_sources(${PROJECT_NAME} PRIVATE
        src/platforms/common/imgui/imgui.cpp
        src/platforms/common/imgui/imgui_demo.cpp
        src/platforms/common/imgui/imgui_draw.cpp
        src/platforms/common/imgui/imgui_tables.cpp
        src/platforms/common/imgui/imgui_widgets.cpp
        src/platforms/common/imgui/backends/imgui_citro3d.cpp
        src/platforms/common/imgui/backends/imgui_ctru.cpp
        src/frontends/imgui_3ds/main.cpp
    )

    ctr_generate_smdh(${PROJECT_NAME}.smdh
        NAME "${PROJECT_NAME} v${PROJECT_VERSION}"
        DESCRIPTION "I hope she made lotsa spaghetti!!!"
        AUTHOR "${APP_AUTHOR}"
        ICON res/3ds/icon.png
    )

    ctr_create_3dsx(${PROJECT_NAME}
        SMDH ${PROJECT_NAME}.smdh
    )
endif()

if (NINTENDO_WII OR NINTENDO_GAMECUBE)
    if (NINTENDO_WII)
        set(WII_LIBRARIES "-lwiiuse -lbte")
    else()
        set(WII_LIBRARIES "")
    endif()

    find_package(PkgConfig REQUIRED)
    pkg_check_modules(FREETYPE REQUIRED freetype2)

    target_link_libraries(${PROJECT_NAME} PRIVATE
        -lpng -lz -lfat ${WII_LIBRARIES} -lasnd -logc -lvorbisidec -logg ${FREETYPE_LIBRARIES})
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_AUDIO=2) # AESND (OGC)

    target_include_directories(${PROJECT_NAME} PRIVATE
        ${DEVKITPRO}/portlibs/${OGC_CONSOLE}/include
        ${DEVKITPRO}/portlibs/ppc/include
        ${DEVKITPRO}/portlibs/ppc/include/freetype2
        src/frontends/gx
    )

    file(GLOB_RECURSE SOURCE_FILES LIST_DIRECTORIES false
        src/frontends/gx/*.cpp
        src/frontends/gx/*.c
    )
    file(GLOB DATA_FILES
        src/frontends/gx/data/fonts/*
        src/frontends/gx/data/images/*
        src/frontends/gx/data/lang/*
        src/frontends/gx/data/sounds/*
    )
    dkp_add_embedded_binary_library(application_data ${DATA_FILES})
    target_link_libraries(${PROJECT_NAME} PRIVATE application_data)
    target_sources(${PROJECT_NAME} PRIVATE ${SOURCE_FILES})

    ogc_create_dol(${PROJECT_NAME})

    if (NINTENDO_WII)
        string(TIMESTAMP PROJECT_BUILDDATE "%Y%m%d000000")
        configure_file(res/wii/meta.xml.in res/wii/meta.xml @ONLY)
    endif()
endif()

if (NINTENDO_WIIU)
    find_package(SDL2 REQUIRED)
    find_package(SDL2_ttf REQUIRED)
    find_package(Freetype REQUIRED)
    include_directories(${DEVKITPRO}/portlibs/wiiu/include ${FREETYPE_INCLUDE_DIRS} ${SDL2_INCLUDE_DIRS} ${SDL2TTF_INCLUDE_DIRS})
    target_link_libraries(${PROJECT_NAME} PRIVATE ${SDL2_LIBRARIES} -lSDL2_ttf -lfreetype -lpng -lz -lm -lharfbuzz -lbrotlidec -lbrotlicommon -lbz2 -lwut)
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_AUDIO=1) # SDL2

    target_include_directories(${PROJECT_NAME} PRIVATE
        src/platforms/common/imgui
    )
    target_sources(${PROJECT_NAME} PRIVATE
        src/platforms/common/imgui/imgui.cpp
        src/platforms/common/imgui/imgui_demo.cpp
        src/platforms/common/imgui/imgui_draw.cpp
        src/platforms/common/imgui/imgui_tables.cpp
        src/platforms/common/imgui/imgui_widgets.cpp
        src/platforms/common/imgui/backends/imgui_impl_sdl2.cpp
        src/platforms/common/imgui/backends/imgui_impl_sdlrenderer2.cpp
        src/frontends/imgui/main.cpp
    )

    wut_create_rpx(${PROJECT_NAME})
    wut_create_wuhb(${PROJECT_NAME}
        NAME "${PROJECT_NAME} v${PROJECT_VERSION}"
        CONTENT res/wiiu/content
        AUTHOR "${APP_AUTHOR}"
        ICON res/wiiu/iconTex.png
        TVSPLASH res/wiiu/bootTvTex.png
        DRCSPLASH res/wiiu/bootDrcTex.png
    )
endif()

if (NINTENDO_SWITCH)
    # -------------------------------------------
    # Switch libraries & include directories
    # -------------------------------------------
    find_package(SDL2 REQUIRED)
    include_directories(${DEVKITPRO}/portlibs/switch/include ${SDL2_INCLUDE_DIRS})

    target_link_libraries(${PROJECT_NAME} PRIVATE
        ${SDL2_LIBRARIES}
        -lnx
        -lm
    )
    target_compile_definitions(${PROJECT_NAME} PRIVATE MINICDI_AUDIO=1) # SDL2

    # -------------------------------------------
    # Source files & ImGui frontend
    # -------------------------------------------
    target_include_directories(${PROJECT_NAME} PRIVATE
        src/platforms/common/imgui
    )

    target_sources(${PROJECT_NAME} PRIVATE
        src/platforms/common/imgui/imgui.cpp
        src/platforms/common/imgui/imgui_demo.cpp
        src/platforms/common/imgui/imgui_draw.cpp
        src/platforms/common/imgui/imgui_tables.cpp
        src/platforms/common/imgui/imgui_widgets.cpp
        src/platforms/common/imgui/backends/imgui_impl_sdl2.cpp
        src/platforms/common/imgui/backends/imgui_impl_sdlrenderer2.cpp
        src/frontends/imgui/main.cpp
    )

    # -------------------------------------------
    # Package generation (.nacp & .nro)
    # -------------------------------------------
    nx_generate_nacp(${PROJECT_NAME}.nacp
        NAME "${PROJECT_NAME}"
        AUTHOR "${APP_AUTHOR}"
        VERSION ${PROJECT_VERSION}
    )

    nx_create_nro(${PROJECT_NAME}
        NACP ${PROJECT_NAME}.nacp
        ICON res/nx/icon.png
    )
endif()
